datasets:
    name: "smplx"
    mesh_folder:
        data_folder: '/home/daniel/Data/PROCESSED_DATA/s05/s05_a08/smplx/'
        
deformation_transfer_path: 'transfer_data/smplx2smpl_deftrafo_setup.pkl'
mask_ids_fname: ''
summary_steps: 100

edge_fitting:
    per_part: False

optim:
    type: 'lbfgs'
    maxiters: 200
    gtol: 1e-06

body_model:
    model_type: "smpl"
    gender: "male"
    ext: 'pkl'
    folder: "/home/daniel/src/transfer_data/meshes"
    use_compressed: False
    use_face_contour: False
    smpl:
        betas:
            num: 10

batch_size: 16